FROM node:10-alpine

WORKDIR /usr/src/app

COPY package*.json ./


COPY . .

EXPOSE 6002
ENV STEAMBOT_TRADE_BOT_ACCOUNT_NAME=nungailu
ENV STEAMBOT_TRADE_BOT_ACCOUNT_PASSWORD=3gyqfJ9zEM
ENV STEAMBOT_TRADE_BOT_IDENTITY_SECRET=gIAaxcBF3pWUYzw1gTkKUP4LyHI=
ENV STEAMBOT_TRADE_BOT_SHARED_SECRET=NtDbOid0FVuYBktHEIDZkEcgFEY=
ENV STEAMBOT_TRADE_BOT_APP_ID=730
ENV STEAMBOT_TRADE_BOT_CONTEXT_ID=2
ENV WAXPEER_API=1e57b79183077b15e0b8e07fae469a15b2fa83f304476b875e5c1896eed7d6dd
ENV NODE_ENV=production
RUN npm install

RUN npm install -g typescript
RUN npm install tsc
RUN npm run tsc
CMD [ "npm", "start"]
